from scripts.fileManagement import mkdir
configfile: "config/config.yaml" 

patients_snsx = config['snsx_patients'].split()
patients_clinic = config['clinical_patients'].split()

mkdir(patients_snsx, config['output_dir'])

graham_dirs = {
    'CBS': '/home/ROBARTS/mcespedes/graham/',
    'graham': '/home/mcesped/'
}
graham_home = graham_dirs['CBS']

def str_sync(wildcards):
    i=patients_snsx.index(wildcards.patients_snsx)
    path = (graham_home+'projects/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/derivatives/atlasreg/'
           f'{patients_clinic[i]}/{patients_clinic[i]}_T1w.nii.gz')
    return path

rule all:
    input: 
        transformT1w = expand(graham_home+'scratch/Test/warps/{patients_snsx}/{patients_snsx}_from-T1w_1_5T_to-T1w_7T.tfm',
                               patients_snsx = config['snsx_patients'].split())

rule get_tf_ClinT1W_to_SNSX:
    input:
        snsx = graham_home+'projects/ctb-akhanf/cfmm-bids/Khan/SNSX_7T/tar2bids_v0.0.5e/correct7T.v0.3/gradcorrect_v0.0.3/{patients_snsx}/anat/{patients_snsx}_acq-MP2RAGE_run-01_T1w.nii.gz'
    output:
        transform = graham_home+'scratch/Test/warps/{patients_snsx}/{patients_snsx}_from-T1w_1_5T_to-T1w_7T.tfm'
    params:
        NxNxN = '100x40x20', # number of iterations per level of multi-res  
        clinic_pat = str_sync,
    shell:
        ('greedy -d 3 -a -m NMI -i {input.snsx} {params.clinic_pat} -o {output.transform} -n {params.NxNxN}'
        ' -ia-image-centers -dof 6')

# rule conv_tf_itk:
#     input: 
#         transformT1w = graham_home+'scratch/Test/warps/{patients_snsx}/{patients_snsx}_from-T1w_1_5T_to-T1w_7T.tfm'
#     output:
#         transform_itk = graham_home+'scratch/Test/warps/{patients_snsx}/{patients_snsx}_from-T1w_1_5T_to-T1w_7T_itk.tfm'
#     shell:
#         ('	c3d_affine_tool -ref ~/graham/projects/ctb-akhanf/cfmm-bids/Khan/SNSX_7T/tar2bids_v0.0.5e/correct7T.v0.3/gradcorrect_v0.0.3/sub-P022/anat/sub-P022_acq-MP2RAGE_run-01_T1w.nii.gz -src ~/graham/projects/ctb-akhanf/cfmm-bids/Khan/clinical_imaging/epi_iEEG/derivatives/atlasreg/sub-P002/sub-P002_T1w.nii.gz ~/graham/scratch/Test/Transforms/sub-P022_from-T1w_to-T1w.mat -oitk ~/graham/scratch/Test/Transforms/sub-P022_from-T1w_to-T1w_itk.mat')