#---- begin snakebids boilerplate ----------------------------------------------

import snakebids
from snakebids import bids
from os.path import join
from itertools import compress
import numpy as np
import sys
sys.path.append('/scratch/mcesped/HippiEEGAtlas/epochs/hippieeg/code')
from file_manager import bids_folder


configfile: workflow.source_path('../config/snakebids.yml')

# Get input wildcards
inputs = snakebids.generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybids_database_dir=config.get("pybids_db_dir"),
    pybids_reset_database=config.get("pybids_db_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    use_bids_inputs=True,
)
subj_session_list = list(zip(inputs.zip_lists['bold']['subject'],inputs.zip_lists['bold']['session']))
input_tsv = snakebids.generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs_tsv"],
    pybids_database_dir=config.get("pybids_db_dir"),
    pybids_reset_database=config.get("pybids_db_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    use_bids_inputs=True,
)

#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(config['pybids_inputs'])
# print(inputs.path)
# print(inputs.zip_lists['bold']['run'])
# print(inputs.zip_lists['bold']['task'])
# print(subj_session_list)
# print(inputs.zip_lists['bold']['subject'])
# print(inputs.zip_lists['bold']['session'])

#---- end snakebids boilerplate ------------------------------------------------
rule epochs:
    input: 
        edf = lambda wildcards: expand(inputs.path['bold'], zip,
	                        session = list(compress(inputs.zip_lists['bold']['session'],
                                        [True if subj == wildcards.subject else False for subj in inputs.zip_lists['bold']['subject']])),
                                task = list(compress(inputs.zip_lists['bold']['task'], 
                                        [True if subj == wildcards.subject else False for subj in inputs.zip_lists['bold']['subject']])),
                                run = list(compress(inputs.zip_lists['bold']['run'], 
                                        [True if subj == wildcards.subject else False for subj in inputs.zip_lists['bold']['subject']])),
                                allow_missing=True),
        tsv = input_tsv.path['bold']
    params:
        script = join(workflow.basedir,'../code/epochs.py'),
        processes = 16
    output:
        directory(
		bids_folder(
	            root=config['output_dir'],
        	    datatype='ieeg',
        	    suffix='channels.tsv',
	            **inputs.wildcards['bold']
        	)
	)
    # log:
    #     bids(
    #         root='/scratch/mcesped/HippiEEGAtlas/epochs/logs',
    #         suffix='epochs.log',
    #         **inputs.wildcards['bold']
    #     )
    shell: 'python {params.script} -p {params.processes} -i {input.edf} -t {input.tsv} -o {output}'

rule all:
    input:
        expand(
            expand(
                rules.epochs.output,
                allow_missing=True,
            ),
            zip,
            **inputs.zip_lists['bold']
        )
    default_target: True
