#---- begin snakebids boilerplate ----------------------------------------------

import snakebids
from snakebids import bids
from os.path import join
from itertools import compress

configfile: workflow.source_path('../config/snakebids.yml')

# Get input wildcards
inputs = snakebids.generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybids_database_dir=config.get("pybids_db_dir"),
    pybids_reset_database=config.get("pybids_db_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    use_bids_inputs=True,
)


#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(config['pybids_inputs'])
print(inputs.path)

zip_list_no_session = inputs.zip_lists
del zip_list_no_session['sessions']

input_wildcards_no_session = inputs.wildcards
del input_wildcards_no_session['session']

#---- end snakebids boilerplate ------------------------------------------------
rule epochs:
    input: 
        lambda wildcards: expand(inputs.path['bold'], session = list(compress(inputs.zip_lists['bold']['sessions'], inputs.zip_lists['bold']['subjects'] == wildcards.subject)), allow_missing=True)
    params:
        script = join(workflow.basedir,'../code/epochs.py')
    output:
        bids(
            root=config['output_dir'],
            datatype='ieeg',
            suffix='epoch.edf',
            **input_wildcards_no_session
        )
    log:
        bids(
            root='/scratch/mcesped/HippiEEGAtlas/epochs/logs',
            suffix='epochs.log',
            **input_wildcards_no_session
        )
    shell: 'python {params.script} {input} {output} &> {log}'

rule all:
    input:
        expand(
            expand(
                rules.epochs.output,
                allow_missing=True,
            ),
            zip,
            **zip_list_no_session
        )
    default_target: True