# ignoring sub-P048
snsx_patients: >
                sub-P022
                sub-P026
                sub-P029
                sub-P032
                sub-P046
                sub-P049
                sub-P051
                sub-P052
                sub-P054
                sub-P055
                sub-P056
                sub-P058
                sub-P059
                sub-P060
                sub-P061
                sub-P070
                sub-P071
                sub-P080
                sub-P081
                sub-P087
                sub-P089
                sub-P090
                sub-P092
                sub-P095
                sub-P097
                sub-P100
#ignoring sub-P007 since I'm ignoring P048
clinical_patients: > 
                sub-P002
                sub-P003
                sub-P002
                sub-P003
                sub-P016
                sub-P004
                sub-P001
                sub-P009
                sub-P013
                sub-P018
                sub-P022
                sub-P021
                sub-P023
                sub-P065
                sub-P067
                sub-P068
                sub-P069
                sub-P078
                sub-P079
                sub-P081
                sub-P082
                sub-P083
                sub-P086
                sub-P087
                sub-P088
                sub-P091
                sub-P093
                sub-P095

# From graham home folder:
output_dir: scratch/Test/

singularity:
  ants: 'docker://kaczmarj/ants:2.3.4'
  c3d: 'docker://nipype/nipype:latest'
  greedy: 'docker://dorianps/itksnap:latest'